[[repos]]
repo = "builtin"
hooks = [
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.14.14"
hooks = [
  {
    id = "ruff-check",
    types_or = ["python"],
    args = ["--fix"]
  },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.9.28"
hooks = [
  { id = "uv-lock" }
]
