# .github/actions/setup-uv/action.yml

name: 'Install UV'
description: 'Installs UV with a specific version'
inputs:
  version:
    description: 'Version of UV to install'
    required: true
    default: '0.10.0'  # Default version if not passed

runs:
  using: 'composite'
  steps:
    - name: 'Install UV'
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.version }}
